### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by NewIncome**
Finished all steps in the Microverse Pathwrite page and the Odin page for this specific project.

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# PULL REQUEST UNDER REVIEW BY ADDO

**Review by Forison — CHANGES_REQUESTED** [review]
## Hi team 👋👋

Nice job but we still need to improve a few things before merging
- check warnings being highlighted by CSS linters in line 27 and 275 of  ```.CSS``` file

- You didn't add a footer in this project😔
> NOTE: In this case, the footer is fixed nav-bar like element fixed at the bottom of the screen with an inscription "Access more of the times by creating a free account or loggin"

-  It uses ```<aside>```  tag for Editor's picks section on the rightmost side. (refer to original page)

- Check your theory of inflation. It is not just a screenshot picture, but rather treat it as 2 rows, each with four columns in which each column has an image and a text beneath it. 
> Remember to use float as well for this implementation
 
#### your project looks good, but kindly do the changes suggested and submit for review again

you are almost there 
🙂Happy coding🙂.

**Review by alissonperes — APPROVED** [review]

**Review by alissonperes — DISMISSED** [review]

**Comment by alissonperes** [comment]
After 6 commits, finnaly fixed all linter errors 🥇

**Review by bolah2009 — APPROVED** [review]
# Awesome job team :clap: 

### It's a :+1: from me.

#### :heavy_check_mark: This project is approved.

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

**Pull request merged**
